# -*- coding: utf-8 -*-
"""Euler method.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XGSHtjqH4aqlYUNm6QvAeaAZf_L5a32Q

Introduction:

Heston Model Simulation via Euler-Maruyama
The Heston Model is a mathematical framework used in quantitative finance to price derivatives by accounting for stochastic volatility. Unlike the Black-Scholes model, which assumes constant volatility, the Heston model treats volatility as a random process that exhibits mean reversion.

1. The Numerical Challenge

Since the Heston model does not have a simple, closed-form solution for path-dependent options, we must rely on Monte Carlo simulation. The Euler-Maruyama (EM) scheme is the most fundamental numerical method for discretizing the Stochastic Differential Equations (SDEs) governing the asset price $S_t$ and its variance $V_t$.However, a major challenge in discretizing the Heston model is the "Leakage" problem: in a discrete time step, the variance process can accidentally become negative. Because the model requires the square root of variance ($\sqrt{V_t}$), a negative value would lead to numerical failure (NaN).
"""

import numpy as np
from .params import HestonParams
from .utils import make_correlated_normals

"""2. Implementation Features

This implementation of the Euler scheme focuses on three key pillars of the course rubrics:Robustness (The Reflection Fix): To handle negative variance, this code implements the Full Reflection technique. If a simulated variance step drops below zero, it is reflected back into the positive domain ($V_{i+1} = |V_{i+1}|$), ensuring the simulation remains stable.Computational Efficiency: The code is fully vectorized using NumPy. Rather than using slow Python loops to iterate through individual paths, it processes the entire vector of $N$ paths simultaneously at each time step to minimize CPU time.Numerical Stability: We simulate the Log-Price ($\ln S_t$) rather than the raw price $S_t$. This ensures that the simulated asset price remains strictly positive and improves the accuracy of the discretization over longer maturities.
"""

def generate_paths_euler(params: HestonParams, n_paths: int, n_steps: int, seed: int = 42):
    rng = np.random.default_rng(seed)
    dt = params.maturity / n_steps

    # Pre-allocate arrays to optimize memory
    S = np.full(n_paths, params.s0)
    V = np.full(n_paths, params.v0)

    for t in range(n_steps):
        # 1. Generate correlated random shocks for this step
        zs, zv = make_correlated_normals(n_paths, params.rho, rng)

        # 2. Variance Update
        v_current = np.maximum(V, 0)

        # Calculate next variance step
        V = v_current + params.kappa * (params.theta - v_current) * dt + \
            params.sigma * np.sqrt(v_current * dt) * zv

        # This is a standard Euler 'fix' for the Heston model
        V = np.abs(V)

        # 3. Asset Price Update (Log-transformed for better numerical stability)
        S = S * np.exp((params.r - params.q - 0.5 * v_current) * dt + \
                       np.sqrt(v_current * dt) * zs)

    return S